### ISSUE TITLE
Are there any concrete tutorials or paper for this works?

### ISSUE THREAD

**Issue by histfuture** [lama-imr/lama#1]
I am not sure how to make this code work as well as what does the database's struct means, are there any corresponding tutorials or papers?

**Comment by galou** [comment]
Did you have a look at  http://wiki.ros.org/Large%20Maps%20Framework? There are no tutorials right now but a good starting point is the source code of the `nlj_dummy` package http://wiki.ros.org/nlj_dummy.

**Comment by histfuture** [comment]
Is this project still maintained?

**Comment by galou** [comment]
Yes, the project is maintained, all issues are solved!
